### ISSUE TITLE
longjump causes uninitialized stack frame

### ISSUE THREAD

**Issue by galenlynch** [timholy/Revise.jl#139]
I saw your the youtube video of your Juliacon talk and have been trying out Revise.jl. Very cool stuff! However, when I use it, I run into segfaults and stack problems that do not occur when I don't. I am using it in the context of a project that uses PyCall to use PyQt. Changing a function to add a simple println debugging statement causes the following crash pretty reliably:

```
*** longjmp causes uninitialized stack frame ***: julia terminated

signal (6): Aborted
while loading no file, in expression starting on line 0
gsignal at /usr/bin/../lib64/libc.so.6 (unknown line)
abort at /usr/bin/../lib64/libc.so.6 (unknown line)
unknown function (ip: 0x7f26c8bc39d6)
unknown function (ip: 0x7f26c8c555ac)
__fortify_fail at /usr/bin/../lib64/libc.so.6 (unknown line)
unknown function (ip: 0x7f26c8c5548c)
__longjmp_chk at /usr/bin/../lib64/libc.so.6 (unknown line)
unknown function (ip: 0x7f26c958e0d4)
jl_rethrow at /usr/bin/../lib64/libjulia.so.0.6 (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 42179395 (Pool: 42174585; Big: 4810); GC: 95
[1]    29519 abort (core dumped)  julia -p 4 -O 3
```

**Comment by galenlynch** [comment]
I'm using it on Julia 0.6.3

**Comment by galenlynch** [comment]
Oh, and I'm using more than one Julia process.

**Comment by timholy** [comment]
Hmm, disturbing failure. 

Believe it or not, Revise's master branch has been 0.7-only since October 2017. The reason is that there are so many goodies we've added to Julia itself in 0.7 specifically to make Revise better that it makes no sense to try to support both. (E.g., method deletion requires 0.7, the source cache in the *.ji files is only on 0.7, etc....). I don't really have the bandwidth to fix bugs on 0.6 (there is a v0.6 branch, and I will merge PRs against it), so I urge you to upgrade to 0.7 and give it another try, either now or whenever you feel comfortable upgrading.

**Comment by timholy** [comment]
Also, if you can give me a complete example I could try myself, it would make a huge difference.

**Comment by galenlynch** [comment]
Upgrading to 0.7 is a daunting prospect... it's not at all clear to me how to migrate my private branch of METADATA to some 0.7 compatible system, and running tests on my only open source package results in page after page after page of deprecation warnings. When I think about doing this for all my julia packages, it seems like quite the investment.

I'll see if I can find some way to reproduce it in a simple manner on 0.6, but if you don't have the bandwidth to support 0.6 I'm happy to just close this bug since I have no idea if it also applies to 0.7.
