### ISSUE TITLE
Don't require sudo for installing package

### ISSUE THREAD

**Issue by GlenHertz** [timholy/Revise.jl#156]
Hi,

I don't have sudo access and the installer wants to expand the maximum number of watched files for which it requires sudo.  The installer fails and I have to run it again.  Please provide a way to bypass sudo so that the installer will complete with success.

Glen

**Comment by GlenHertz** [comment]
During install when the issue is printed out to the terminal, can you ask the user if they want to do it or not and allow them to bypass it without the error?

**Comment by timholy** [comment]
No, unfortunately `build.jl` is non-interactive except for the ability to enter a password. Heck, just to print the explanation of why it was asking for your password, I had to circumvent our ordinary print methods and [send it straight to the tty via a shell command](https://github.com/timholy/Revise.jl/blob/ae04e84ab5fa99b1ed57ffa246340367067a8d5c/deps/build.jl#L16).

I'd love it if it were more interactive: I'd like to ask users whether they want to add the automatic startup to their `.julia/config/startup.jl` as well, and one could conceivably even ask about some of the [other settings](https://timholy.github.io/Revise.jl/latest/config.html#Configuration-options-1). Then once configured, one could write a file so that the user wouldn't be bothered again. CC @KristofferC.

**Comment by timholy** [comment]
I *can* turn this off. I was just annoyed by bug reports about it not working. And I did set up a mechanism so you can prevent yourself from being annoyed.

**Comment by tkf** [comment]
I had the same problem.  It would be nice if I can set

```julia
ENV["REVISE_ASK_USER_WATCHES"] = "no"
```

to turn it off.  Finding `~/.julia/packages/Revise/.../deps/` to create `user_watches` is a bit tedious with Pkg3.

**Comment by timholy** [comment]
Sure, if that's easier. I've sometimes wondered if it would be better to have a config file, though, than setting all the `ENV` variables. Thoughts?

**Comment by tkf** [comment]
@timholy I totally agree that configuration via `ENV` is not great. It would be really nice if "package option" is supported by Pkg3 https://github.com/JuliaLang/Juleps/issues/38

**Comment by tkf** [comment]
How about `@warn`ing in `__init__` and running `sudo` in `async_steal_repl_backend`?

I think it makes sense to do the check at run-time since it looks like `max_user_watches` can be reset after reboot in some environments: https://askubuntu.com/questions/716431/inotify-max-user-watches-value-resets-on-reboot-how-to-change-it-permanently

**Comment by GlenHertz** [comment]
Great. This will even cover the case where the user is running on a different machine than the installer. Thanks Tim!

**Comment by timholy** [comment]
I just hope I wrote the check for the error correctly! This is a very hard one to catch.
