### ISSUE TITLE
`task_local_storage` issue

### ISSUE THREAD

**Issue by mdashti** [timholy/Revise.jl#196]
When I run the following line in a fresh Julia (0.7) REPL:

```julia
julia> using Revise; task_local_storage(:testkey, "test_val")
"test_val"
```

Then, `task_local_storage` is empty, e.g.:

```julia
julia> keys(task_local_storage())
Base.KeySet for a IdDict{Any,Any} with 1 entry. Keys:
  :SOURCE_PATH
```

However, if I run the above command again (in the same REPL)

```julia
julia> using Revise; task_local_storage(:testkey, "test_val")
"test_val"
```

`task_local_storage` contains the expected element this time, e.g.:

```julia
julia> keys(task_local_storage())
Base.KeySet for a IdDict{Any,Any} with 2 entries. Keys:
  :SOURCE_PATH
  :testkey
```

It's interesting that the above issue does not happen if I run `using Revise` as a separate command first, e.g., in a fresh REPL:

```julia
julia> using Revise

julia> task_local_storage(:testkey, "test_val")
"test_val"

julia> keys(task_local_storage())
Base.KeySet for a IdDict{Any,Any} with 2 entries. Keys:
  :SOURCE_PATH
  :testkey
```

Here is the output of `versioninfo()` for me:
```julia
julia> versioninfo()
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

**Comment by timholy** [comment]
This isn't really a bug, or perhaps it's better to say it's an unfixable bug. Revise has to replace the REPL loop with its own (so that `revise` gets triggered after every user input), and that creates a new task that is then operative henceforth in the REPL. In your first version, that task hasn't been created yet when your command gets `eval`ed.

As you say, all you have to do here is start Revise first, let it set up its own task, and then you can set the storage. The easy way to achieve this is have Revise start when the REPL does, see https://timholy.github.io/Revise.jl/stable/config.html#Using-Revise-by-default-1.

**Comment by timholy** [comment]
If this is causing a problem for some other context, feel free to amplify with more detail and I can re-open if necessary.

**Comment by mdashti** [comment]
Thanks @timholy for the explanation. Now it makes sense.
