### ISSUE TITLE
Delete (non-constant?) variables from tracked files

### ISSUE THREAD

**Issue by MasonProtter** [timholy/Revise.jl#224]
So Revise will automatically detect that methods I've declared in a tracked file were removed and then delete them from the method table. Is there a reason Revise doesn't do the same for variables that were declared in a tracked file and then deleted?

**Comment by timholy** [comment]
There's no support for this in Julia. But of course, we can delete methods because Jameson and I added it, so of course that's something that could change.

What's the use-case for deleting variables inside a module? It's actually a much harder case to handle: if you delete a method you don't delete the binding of the function itself. Here, I think you're asking to delete a binding.

**Comment by MasonProtter** [comment]
Right, I should have thought more carefully about this before making the issue. I had forgotten that Julia does not like removing bindings. I just naïvely thought it would be more symmetric if revise could remove variable bindings as well as methods, but I guess the whole reason it can delete methods but not functions is because because we cant remove bindings.
