### ISSUE TITLE
includet fails when file is opened in subdirectory

### ISSUE THREAD

**Issue by aterenin** [timholy/Revise.jl#264]
To reproduce do the following.

1. Open an Atom project and create a subfolder `code` in that project.
2. Create a file `code/code.jl` in that subfolder.
3. Create a file `code/imports.jl` also in that subfolder.
4. Open `code.jl` in Atom, add the like `includet("imports.jl")`, and run.

The error given is `xxxxxx.jl is not a file`. On the other hand, using `include` works fine.

If we change the code to instead say `includet("code/imports/jl")` then Julia will instead attempt to import `code/code/imports` which doesn't exist.

**Comment by timholy** [comment]
I think you have a typo; `includet("code/imports.jl") (note the dot rather than the slash) works for me.

But I fixed this in #276. Also a note, if you're using complex paths, you might want to consider just making that code a package and then Revise will do it all automatically when you use `using` or `import`. `includet` is really intended for quick hacks.

**Comment by aterenin** [comment]
Sorry, typo is only present in MWE and not my code.

Thanks for the quick fix!
