### ISSUE TITLE
Naming conflict?

### ISSUE THREAD

**Issue by JianghuiDu** [timholy/Revise.jl#283]
I `includet` my own script and get the following error. It looks like `Revise` causes a conflict between the variable `alpha` I define in my script with the argument `alpha` in package `Colors`  in the main module (I simply add `using Colors` without even using any functions from it.). Without `using Revise` my code runs fine.

```
┌ Warning: error evaluating in module Main: const alpha = alpha_0 * exp.(-(x_mid .^ 2) / (2 * x_bt ^ 2)) * f_Db
│   exception =
│    cannot assign variable ColorTypes.alpha from module Main
```

**Comment by JianghuiDu** [comment]
OK. The problem is solved if I move `using Revise` to the top. Maybe this should be made clear in the Docs.

**Comment by timholy** [comment]
A pull request to clarify the docs would be most welcome! You can just click the pencil icon on any of the files and edit it in your browser.

**Comment by ctkelley** [comment]
I'm having the same problem and am not using Revise. I'm getting
julia> alpha=1.0; beta=1.0;
ERROR: cannot assign variable ColorTypes.alpha from module Main
Stacktrace:
 [1] top-level scope at none:0

Restarting Julia seems to make the problem go away (sometimes)

**Comment by timholy** [comment]
This is expected. ColorTypes exports a function alpha to extract the alpha channel. Either don't use a variable called alpha or say `import ColorTypes` and scope all calls with the module name.

**Comment by ctkelley** [comment]
Now I'm really confused. Alpha is a pretty common variable name. Is it illegal in Julia?

In any case, how do I " scope all calls with the module name "?

**Comment by tk3369** [comment]
When you `using` a package, you bring all exported names from the package to your current scope.  That's why it's giving your a conflict.
```
julia> using ColorTypes

julia> alpha
alpha (generic function with 5 methods)

julia> const alpha = 1
ERROR: cannot assign variable ColorTypes.alpha from module Main
```

Note that if `alpha` was not referenced before, then it's not a "problem" and you will have to use `ColorTypes.alpha`.
```
julia> using ColorTypes

julia> const alpha = 1
1

julia> ColorTypes.alpha
alpha (generic function with 5 methods)
```

If you really want to use `alpha` in your own program, then you have an option to not import the name from ColorTypes.

```
julia> import ColorTypes

julia> alpha
ERROR: UndefVarError: alpha not defined

julia> const alpha = 1
1

julia> ColorTypes.alpha
alpha (generic function with 5 methods)
```

One way to "solve" this problem is to only bring in specific names to your scope.  When you do that, you will know mentally that the name `alpha` is already taken and has a meaning, and so you will naturally avoid using it.
```
julia> using ColorTypes: alpha

julia> const alpha2 = 1
1
```

**Comment by ctkelley** [comment]
Thanks for the fast response. The problem is not consistent. I just started Julia and 

julia> alpha=1;

was fine. alpha and beta are kinda natural variables to use. For example

help?> gemm!
search: gemm! gemm

  gemm!(tA, tB, alpha, A, B, beta, C)

  Update C as alpha*A*B + beta*C or the other three variants according to tA
  and tB. Return the updated C.

Is there something I could be doing that imports ColorTypes unintentionally? Is it only a problem in the REPL?

**Comment by fredrikekre** [comment]
Please direct general Julia questions to https://discourse.julialang.org/.
