### ISSUE TITLE
Revise re-runs before parsing input at REPL

### ISSUE THREAD

**Issue by goretkin** [timholy/Revise.jl#320]
I haven't confirmed, but it seems that Revise updates any tracked files before the just-entered line at the REPL is parsed.

I would prefer to get a quicker syntax error about the line I just entered, and then have Revise run only after the line parses.

**Comment by timholy** [comment]
The logic here is two lines of code: https://github.com/timholy/Revise.jl/blob/d160813bed054d80fe29854a3178fb726b3e808b/src/Revise.jl#L946-L949. Parsing is done by the time it gets `ast`, but of course there's more to the evaluation than just parsing.

Since people want changes to take place before running the new code, I don't think this is possible. Can you give me an example of how this causes a problem?

**Comment by goretkin** [comment]
The only problem is not failing fast. If I make a syntax error on the REPL, and I made some long-to-evaluate change to the tracked files, it takes a while to receive the syntax error. The only issue is that the error could have been reported immediately.

I don't remember which syntax error I had in mind, but I don't understand how I experienced my issue if parsing seems to happen on this line: https://github.com/timholy/Revise.jl/blob/d160813bed054d80fe29854a3178fb726b3e808b/src/Revise.jl#L941

**Comment by timholy** [comment]
Most revisions should be fast, once the code in Revise & its dependencies has compiled. Unfortunately with Revise 2 the dependency chain is large so the first one has quite a long delay.

I don't think there's anything actionable here, so I'll close pending further thoughts.
