### ISSUE TITLE
Revise doesn't pick up changes in compiler/tfuncs.jl

### ISSUE THREAD

**Issue by Keno** [timholy/Revise.jl#378]
I'm not entirely sure what the issue, but if I `Revise.track(Core.Compiler)` and then make a change to tfuncs.jl, e.g.:
```
diff --git a/base/compiler/tfuncs.jl b/base/compiler/tfuncs.jl
index a9543bcac4..b07d59c7bd 100644
--- a/base/compiler/tfuncs.jl
+++ b/base/compiler/tfuncs.jl
@@ -1427,7 +1427,7 @@ end
 # TODO: this function is a very buggy and poor model of the return_type function
 # since abstract_call_gf_by_type is a very inaccurate model of _method and of typeinf_type,
 # while this assumes that it is an absolutely precise and accurate and exact model of both
-function return_type_tfunc(argtypes::Vector{Any}, vtypes::VarTable, sv::InferenceState)
+function return_type_tfunc(interp::AbstractInterpreter, argtypes::Vector{Any}, vtypes::VarTable, sv::InferenceState)
     if length(argtypes) == 3
         tt = argtypes[3]
         if isa(tt, Const) || (isType(tt) && !has_free_typevars(tt))
@@ -1442,9 +1442,9 @@ function return_type_tfunc(argtypes::Vector{Any}, vtypes::VarTable, sv::Inferenc
                     end
                     astype = argtypes_to_type(argtypes_vec)
                     if isa(aft, Const)
-                        rt = abstract_call(aft.val, nothing, argtypes_vec, vtypes, sv, -1)
+                        rt = abstract_call(interp, aft.val, nothing, argtypes_vec, vtypes, sv, -1)
                     elseif isconstType(aft)
-                        rt = abstract_call(aft.parameters[1], nothing, argtypes_vec, vtypes, sv, -1)
+                        rt = abstract_call(interp, aft.parameters[1], nothing, argtypes_vec, vtypes, sv, -1)
                     else
                         rt = abstract_call_gf_by_type(nothing, argtypes_vec, astype, sv, -1)
                     end
```
it doesn't get picked up (manually doing the update using Core.eval works fine). I'm not sure what the issue is, but I did note that the top of the file has a `@nospecialize` which may throw off Revise.

**Comment by timholy** [comment]
https://github.com/timholy/Revise.jl/blob/1102fbde9e3a145782ec102e438f1d5d079ca30f/src/recipes.jl#L136

The problem is that Revise 2.0 discovers `:method` Exprs by stepping through the lowered code that defines the module. That was the key step finally providing proper support for lowered variants of keyword-arg methods, `@eval`-generated methods, etc., BUT that also means it repeats any work as a side effect, and that's bad bad on `tfuncs.jl`. (See discussion in #289.)

One likely fix is to get smarter and do only the work needed to compute method signatures, and ignore all other toplevel code. The key step is probably finishing #255. But perhaps you can suggest a simple workaround?
