### ISSUE TITLE
Packages with fancy `include` mechanisms

### ISSUE THREAD

**Issue by cstjean** [timholy/Revise.jl#40]
Followup to https://github.com/timholy/Revise.jl/pull/10#issuecomment-313971103. Both [`DataFrames.jl`](https://github.com/JuliaStats/DataFrames.jl/blob/master/src/DataFrames.jl#L74-L99) and [`Plots.jl`](https://github.com/JuliaPlots/Plots.jl/blob/b585a0ef61b1af1308cf7ebf0f746c42b39d3869/src/backends.jl#L28) include files through complicated mechanisms. Plots.jl might be a challenge to handle reliably.

> I wondered when this would come up. One option is to put a @require Revise, or a isdefined(Main, :Revise) in the __init__ file, and then having DataFrames add the files "manually" with Revise.track(DataFrames, filename).

Revise.jl is already hooking into `using` to detect that a package is loaded. Is there a way to do the same with `include`?

**Comment by timholy** [comment]
In theory, yes, but you'll get a warning every time Julia starts that you've redefined [this method](https://github.com/JuliaLang/julia/blob/943c8e57753022213b08a6e67faccdad5572d723/base/loading.jl#L458-L473). That's because we'd have to duplicate it and then insert a bit of code to log the file as having been included.

Alternatively we could petition Base to insert a hook mechanism here too. Ref https://github.com/JuliaLang/julia/pull/21441.

**Comment by cstjean** [comment]
This would also be the only way we could support files that are included interactively, right? 

> In theory, yes, but you'll get a warning every time Julia starts that you've redefined this method. 

We could silence it.

**Comment by timholy** [comment]
https://github.com/JuliaLang/julia/pull/23898
