### ISSUE TITLE
suppress "revise is not tracking" warnings after first time

### ISSUE THREAD

**Issue by ssfrr** [timholy/Revise.jl#438]
Sometimes when the code changes (e.g. when I update packages) there will be some problem that Revise doesn't know how to handle, so I get warnings of the form "Due to a previously reported error, the running code does not match saved version for the following files ..." with a list of files. Sometimes the files it's warning be about are for features I'm not using, so it would be great to have a way to disable those warnings after the first time they're displayed. As it is now they display every time I run code at the REPL.

**Comment by timholy** [comment]
This is the exact opposite request of #317 and #321; I didn't make it optional because the more options software has the more of a Rube Goldberg contraption it becomes. And Revise already has a lot of options. But I can see why you might want this.

I can't tell how specific you want this to be; just for some issues or globally? If you design an API for how you want this to work, I can either do or help with the implementation. FYI the code that issues the warning is https://github.com/timholy/Revise.jl/blob/01ce17d293cbb551ad70746a65e274c41df00be9/src/Revise.jl#L641-L650. Suppressing the warning is not the hard part, it's deciding how this should be configured.
