### ISSUE TITLE
Can't compile latest Revise

### ISSUE THREAD

**Issue by atgmello** [timholy/Revise.jl#468]
It seems like versions 2.6.1 and later are having some issues with `CodeTracking`.
Reverting back to v2.6.0 I can compile Revise just fine.

Error:
```julia
(plot) pkg> st
    Status `~/git/DEParamEst/src/plot/Project.toml`
  [295af30f] Revise v2.6.4

(plot) pkg> precompile
Precompiling project...
Precompiling Revise
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
ERROR: LoadError: UndefVarError: line_is_decl not defined
Stacktrace:
 [1] include at ./boot.jl:328 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1105
 [3] include(::Module, ::String) at ./Base.jl:31
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:330 [inlined]
 [6] eval(::Expr) at ./client.jl:425
 [7] top-level scope at ./none:3
in expression starting at /home/andrew/.julia/packages/Revise/WkyNB/src/Revise.jl:17
```
Besides v2.6.4, I can confirm that the same error is present in v2.6.1, v2.6.2 and v2.6.3 as well.

`versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 16
```

**Comment by timholy** [comment]
Something is holding back your CodeTracking. This feels like a Pkg bug, since 2.6.1 requires CodeTracking 0.5.9 which provides `line_is_decl`. https://github.com/timholy/Revise.jl/compare/v2.6.0...v2.6.1

If you can debug this it would be great, as it might lead to discovery of a deeper bug somewhere in the Pkg dependency system. Make sure you start from a fresh Julia session, though, in case it's just a loading order thing as described in #461.

**Comment by atgmello** [comment]
I was just about to close this issue and apologize for not spotting #461 earlier but maybe this is not exactly the case. Or rather, this issue does seem to be related with Juno.

Starting from a fresh REPL I cannot reproduce this behaviour. 

1. Launch julia REPL.
1. `(v1.3) pkg> ./revise_repl`
1. `(revise_repl) pkg> add Revise`
1. `(revise_repl) pkg> precompile`
1. `julia> using Revise`

No issues.
But then from a fresh Juno:

1. Launch Juno.
1. `(v1.3) pkg> ./revise_juno`
1. `(revise_juno) pkg> add Revise`
1. `(revise_juno) pkg> precompile`

And with that I get the error I originally posted.
How may I proceed with the debugging?

**Comment by KristofferC** [comment]
> Something is holding back your CodeTracking. This feels like a Pkg bug, since 2.6.1 requires CodeTracking 0.5.9 which provides line_is_decl.

I really doubt it. Cases like this almost always occur due to the same reason as I mentioned in https://github.com/timholy/Revise.jl/issues/461#issuecomment-617886385.

To be explicit:

- A certain version of CodeTracking is installed in the global environment.
- Juno starts, loads some dependencies including CodeTracking (maybe for the debugger functionality).
- The user changes environment and loads Revise
- Loading Revise will now try to load CodeTracking but since CodeTracking is already loaded in the Julia session, the already loaded one will be used which potentially is incompatible with Revise in the current project.

This is a drawback to the way Juno works (loading stuff into your Julia session).
Mixing loading packages and changing projects in a running session is never really "safe" in the sense of that there are no incompatibilities.

**Comment by timholy** [comment]
Thanks for explaining in greater detail, I didn't get it from the original.

Personally, I'd still call this a loading/Pkg bug. To me it seems the `[compat]` checks should be run on already-loaded modules, and an error `Cannot load Revise 2.6.4 when CodeTracking 0.5.8 is already loaded; you may have switched to an incompatible project environment` should be thrown.

**Comment by timholy** [comment]
xref https://github.com/JuliaLang/julia/issues/35663

**Comment by timholy** [comment]
I'm going to close this since there's nothing for Revise to do here; the fix must be elsewhere. @atgmello, try updating your packages and possibly ...

oh, see you just did that! Great!
