### ISSUE TITLE
Branch-safe Revise

### ISSUE THREAD

**Issue by Byrth** [timholy/Revise.jl#472]
I commonly am in this situation:
1) I've been working for an hour or two on a branch and the final tests have been kicked off in REPL
2) Now I'd like to do a code review on a different branch

This is not a problem with careful use of Revise. Unfortunately, however, I am a bit of a buffoon. Thus, when I change the branch, review code, and later return to the REPL to analyze my results without remembering to flip back, Revise interprets all the changes to my Repo since the last command (the branch change) and throw a bunch of errors.

One solution to this problem would be to have Revise monitor the checked out branches for repositories being developed and ignore revisions to them if their branch has changed. Ideal solution for me would to let it be togglable behavior so I'm not stuck rebooting my REPL after I merge a feature to #master and switch to a fresh branch.

Just throwing this out there as a suggestion because it has happened to me more than a few times and if there's one thing all buffoons know, it's that we're not alone.

**Comment by timholy** [comment]
The problem is, I frequently *want* Revise to implement changes between branches. For example if you want to see if a branch fixes an error that's been reported on `master`, it's quite convenient to switch branches and run the same test again.

My view is that the best long-term plan is to keep the current behavior but get Revise to the point where it can follow any kind of change. That's a tall order and won't be reached soon. So if you want to do something to make this configurable, that might be a good intermediate station. I'm not quite sure what that should look like. If you want to play with solutions yourself, maybe start hacking on [`watch_manifest`](https://github.com/timholy/Revise.jl/blob/26f14fe951631f4dd33bab83b26dc1d5e5e84dcb/src/pkgs.jl#L487-L539).

**Comment by timholy** [comment]
You might also keep track of the kind of things that trip Revise up. Anything listed on https://timholy.github.io/Revise.jl/stable/limitations/ doesn't need to be reported; any other problem should be viewed as a bug.

**Comment by Byrth** [comment]
Got it, thanks!
