### ISSUE TITLE
Revise doesn't track imports with a precompiled sysimage.

### ISSUE THREAD

**Issue by TommyXR** [timholy/Revise.jl#549]
Hi,

I've been using Revise for a few months now, and until today everything was working fine.

I am using a custom sysimage with only `OhMyREPL` and `Revise` included.

![image](https://user-images.githubusercontent.com/42289375/95002691-d1595480-05a4-11eb-856a-725ca2f90ed5.png)

It seems like Revise fails to track included packages when using the precompiled sysimage. `includet`-ing them manually does work as expected though.

Also, if I use the default sysimage, everything works fine. 
![image](https://user-images.githubusercontent.com/42289375/95002697-fd74d580-05a4-11eb-9232-5570212e0034.png).

This is really unexpected, as nothing in my julia install had changed when I started encountering this.

Now I updated all my packages, recompiled a new sysimage, and the problem is still there.

Julia version: 1.5.1 (tarball)
Revise version: 3.1.2
System: Debian (Bullseye)

**Comment by timholy** [comment]
Here's the reason: https://github.com/timholy/Revise.jl/blob/b18fc4c06072c4d27c0301f5fb1138abbbc46448/src/packagedef.jl#L1345-L1355

You can "fix" the problem with
```julia
julia> id = Base.PkgId(Revise)
Revise [295af30f-e4ad-537b-8983-00126c2a3abe]

julia> Revise.swap_watch_package(id)
watch_package (generic function with 1 method)
```
before you load any packages. (I'm not recommending this as a long-term fix, just pointing out that it verifies the diagnosis.)

@KristofferC, any ideas about how to handle this? All the other initialization works out fine. Does PackageCompiler need to execute `Base.package_callbacks` while generating the sysimage?

**Comment by timholy** [comment]
That said, you may find that the new Revise loads quickly enough (esp. on Julia 1.6) that it's not a big deal. If you do want to build a sysimage, I highly recommend making sure you precompile `revise()` before generating the sysimage, since that's now the only part of Revise's pipeline that feels really slow.

**Comment by TommyXR** [comment]
Thank you for the quick answer and the temporary fix!

When I added Revise to my sysimage, it was still slow at startup (which doesn't matter when working on a project, but it does when you just want a quick REPL session to try something quickly), but I haven't tried again for a while. I will gladly try it out when I upgrade to 1.6.

**Comment by KristofferC** [comment]
> Does PackageCompiler need to execute Base.package_callbacks while generating the sysimage?

I thought this would happen automatically when the packages get loaded into the process that generates the sysimage. I'll experiment and see what is going on.

**Comment by KristofferC** [comment]
Revise assumes that there will be a `package_callbacks` invocation with itself as the "pkgid" exactly after its `__init__` method has been run to swap out the fake callback to the true one. This is not true when Revise is in the sysimage. With regards to https://github.com/JuliaLang/PackageCompiler.jl/issues/451, there is nothing really that PackageCompiler can do about that because the issue is with the final sysimage at which point PackageCompiler is out of the picture.
