### ISSUE TITLE
Warning on today's master

### ISSUE THREAD

**Issue by PallHaraldsson** [timholy/Revise.jl#559]
FYI: I'm not sure you're aware (I was just downloading master again to compile):

```
  0.528193 seconds (481.90 k allocations: 31.350 MiB, 39.47% compilation time)
┌ Warning: error while importing Revise
│   e =
│    InitError: MethodError: no method matching Base.TOMLCache()
│    Closest candidates are:
│      Base.TOMLCache(::Base.TOML.Parser, ::Dict{String, Base.CachedTOMLDict}) at loading.jl:215
│      Base.TOMLCache(::Any, ::Any) at loading.jl:215
│    during initialization of module Revise
└ @ Main ~/.julia/config/startup.jl:5
```

And FYI (nice touch with the spinning wheels, I thought this was a new feature in master, but seems only in your package for parallelism), result:

```
(@v1.6) pkg> test Revise
Precompiling project... (tip: to disable auto-precompilation set ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0)
  PackageCompiler ✗
  BPFnative ✗
  OpenCV ✗
324 dependencies successfully precompiled, 3 errored (11 already precompiled)

ERROR: The following direct dependencies failed to precompile:
  PackageCompiler [9b87118b-4619-50d2-8e1e-99f35a4d4d9d]
  BPFnative [b6338580-32ea-11e9-1791-33a79977d8c4]
  OpenCV [3ad7be9e-c11c-11e8-3816-394ce09261e1]
```

**Comment by timholy** [comment]
It's already fixed in Revise 3.1.5, released yesterday.

I don't deserve any credit for the spinning wheels, that's all @ianshmean (on master, as you say) with additional thanks to the kind folks who have been reviewing his awesome PRs. I think you just happened to see it here somehow.

The precompile errors are not in packages that Revise depends on, they are ones in your personal environment. Any time you have precompile errors, you'll always see such messages no matter which package you decide to test.
