### ISSUE TITLE
Revise failure when adding module and relative import

### ISSUE THREAD

**Issue by yha** [timholy/Revise.jl#627]
After adding this (valid) code inside a tracked module
```
module Foos
    struct Foo end
end
using .Foos: Foo
```
revising fails with `Foo not defined`.

**Comment by timholy** [comment]
Can you be a bit more explicit? I tried adding this to the "Namespace" tests:
```diff
diff --git a/test/runtests.jl b/test/runtests.jl
index 8845537..1659eb0 100644
--- a/test/runtests.jl
+++ b/test/runtests.jl
@@ -758,7 +758,7 @@ end
     end
 
     do_test("Namespace") && @testset "Namespace" begin
-        # Issues #579 and #239
+        # Issues #579, #239, and #627
         testdir = newtestdir()
         dn = joinpath(testdir, "Namespace", "src")
         mkpath(dn)
@@ -767,6 +767,11 @@ end
             module Namespace
             struct X end
             cos(::X) = 20
+            # From #627
+            module Foos
+                struct Foo end
+            end
+            using .Foos: Foo
             end
             """)
         end
@@ -781,6 +786,11 @@ end
             struct X end
             sin(::Int) = 10
             Base.cos(::X) = 20
+            # From #627
+            module Foos
+                struct Foo end
+            end
+            using .Foos: Foo
             end
             """)
         end
```
but the test passed.

**Comment by yha** [comment]
The failure is when this code snippet is added to a module where is wasn't previously. Try adding it only the second time:
```
--- a/test/runtests.jl
+++ b/test/runtests.jl
@@ -758,7 +758,7 @@ end
     end

     do_test("Namespace") && @testset "Namespace" begin
-        # Issues #579 and #239
+        # Issues #579, #239, and #627
         testdir = newtestdir()
         dn = joinpath(testdir, "Namespace", "src")
         mkpath(dn)
@@ -781,6 +781,10 @@ end
             struct X end
             sin(::Int) = 10
             Base.cos(::X) = 20
+            module Foos
+                struct Foo end
+            end
+            using .Foos: Foo
             end
             """)
         end
```

**Comment by timholy** [comment]
Thanks, very helpful. I know what the issue is: Revise organizes expressions by module before doing the evaluation, and this is an ordering issue where the changes to `NameSpace` get evaluated before the expression that defines `Namespace.Foos`. If Revise kept file-order this wouldn't be a problem.

Order in general is tricky (the reason for `Revise.retry()`), as changes sometimes occur across files and packages. I'll think a bit about this; the two best options seem to be:
- rework internal data structures to preserve order
- increase `revise()`'s flexibility about order, always going on to the next expression if one fails and then coming back for a second (or third, or...) pass to try the remaining failures.
