### ISSUE TITLE
Move to JuliaLang Github Organization

### ISSUE THREAD

**Issue by mkitti** [timholy/Revise.jl#768]
We should considering moving Revise.jl to https://github.com/JuliaLang. Some indicators include the following.

* It's mentioned in the official documentation: https://docs.julialang.org/en/v1.9/manual/workflow-tips/#Revise-based-workflows
* It's supported by the [julia-vscode](https://github.com/julia-vscode/StaticLint.jl/pull/373) [extension](https://github.com/julia-vscode/julia-vscode/pull/2347)

**Comment by mkitti** [comment]
We as in the community, or perhaps effectively, whomever has maintainership over this package, which is quite unclear at the moment.

Why is  https://github.com/JuliaLang/PrecompileTools.jl in the JuliaLang organization and not Revise.jl?

**Comment by mkitti** [comment]
The problem is as @ChrisRackauckas [stated](https://discourse.julialang.org/t/are-revise-packagecompiler-and-pkg-part-of-julia-and-how-do-we-better-share-them/99491/) on Discourse of how do people determine if Revise.jl is "part of Julia" or not.


Quoting @timholy 's [response](https://discourse.julialang.org/t/are-revise-packagecompiler-and-pkg-part-of-julia-and-how-do-we-better-share-them/99491/18):

> I suppose we could move Revise to JuliaLang, if there’s a general consensus that it’s better there. But where do you draw the line? To me, Cthulhu and JET seem to be in the same camp as Revise. My suspicion is that JET in particular will come to occupy a much more central role once we get full static compilation. In the long term, I think PackageCompiler will go away, but JET will only grow in importance.

I would like to gauge here if a general consensus now exists.

**Comment by ufechner7** [comment]
> Who are "we" here? I don't see why any of your points warrants a move of the repo. I don't think this needs to be an open issue since there isn't really anything to fix.

Well, it would be good if it would be clear that Revise is a core part of the Julia language ecosystem, and not just a hobby project of some private developer... And moving the repo could make this more clear.

**Comment by stevengj** [comment]
To me, once a package becomes widely used, it should really be moved into some organization (JuliaLang or other), if only to have multiple owners potentially able to step in if the original maintainer moves on.

**Comment by rben01** [comment]
Revise is a core part of using Julia — it's even [part of the official docs](https://docs.julialang.org/en/v1/manual/workflow-tips/#Revise-based-workflows) (see below)! I think once a package is recommended in the official docs, it should probably be moved under JuliaLang, both to indicate that it's quasi-official (and it is, since the docs recommend it) and to place it under a larger group of people than just @timholy.

> Whether you're at the REPL or in IJulia, you can typically improve your development experience with [Revise](https://github.com/timholy/Revise.jl). It is common to configure Revise to start whenever julia is started, as per the instructions in the [Revise documentation](https://timholy.github.io/Revise.jl/stable/).

As for other “core-ish” packages like JET and Cthulhu, my guess is that they are not nearly as core as Revise. When it comes to developer experience, JET and Cthulhu are nice-to-haves, whereas Revise is simply a necessity. Furthermore, JET and Cthulhu seem rather experimental and unstable at this point in time, whereas Revise is quite stable.

**Comment by StefanKarpinski** [comment]
This seems like a fine idea to me. At the very least, it should be moved out of @timholy's personal GitHub account. We really shouldn't have key pieces of ecosystem infrastructure that aren't in some kind of org.

**Comment by DaniGlez** [comment]
I believe that Revise is a step above the mentioned analysis packages in terms of spread, if only because it's a default addition to the integrated REPL with the Julia extension for VS Code.

**Comment by timholy** [comment]
I'd be happy to move Revise to JuliaLang once it can be implemented sanely. But currently it's insanely heroic and requires a huge software stack. There are also relatively few people who are able/willing to maintain Revise, and I think all of them already have full commit access.

**Comment by LilithHafner** [comment]
Triage says that we should move this to JuliaLang to signify that it is a core part of the Julia language tooling and such and so that more than one person has owner permissions. Nobody at the meeting would be willing to die on this hill, but we all agree that it would be good.

There is no requirement that things in the JuliaLang org be sane. ;)
