### ISSUE TITLE
"UNHANDLED TASK ERROR: TaskFailedException" when running extra tests

### ISSUE THREAD

**Issue by topolarity** [timholy/Revise.jl#859]
This looks like a silent failure potentially: https://github.com/timholy/Revise.jl/actions/runs/11161822679/job/31025180765#step:9:69

1.6 CI looks fine, but it's present on multiple OS's for 1.9, 1.11, and nightly

**Comment by timholy** [comment]
Yeah, this has been there for a long time. If memory serves, it came from more recent Julia's being picky about exiting with unfinished Tasks; those tests start a repl. When I last looked, and it seemed that the solution was to insert a mechanism into the REPL to allow an external agent to trigger an exit. I.e., `eval_next_input[] || return nothing`. I'm not sure if anyone would ever launch more than one repl task, but ideally that might be a kwarg rather than a global.
