### ISSUE TITLE
Callbacks for changes [feature suggestion]

### ISSUE THREAD

**Issue by essenciary** [timholy/Revise.jl#93]
It would be useful to allow registering callbacks so that other parts of the app would be notified of changes. This would allow the reuse of Revise's functionality for other features, without the need to set up extra file watchers.

**Comment by essenciary** [comment]
A very good example here is implementing a web page live reload functionality. Traditionally, these work by monitoring web app files for changes -- but since Revise already does this (and also includes package files, not just app files), it would be more powerful to hook into the Revise life cycle. 

I'm working on live reload for Genie and I could really use these hooks.

**Comment by timholy** [comment]
That's an interesting idea. Are all the changes you want to know about in Julia code, though, or are you including other languages too? Revise can only handle Julia expressions.

**Comment by essenciary** [comment]
Only Julia code - changes in frontend files (CSS, JS) are handled by specific tools (like say Webpack) which take care of building (like from say SASS or ECMAScript to pure CSS and JS, on the fly) and reloading. So I wouldn't bother with the rest, best if we focus on the Julia parts and do it right.

**Comment by timholy** [comment]
Because I don't know anything about web development, I think I'm going to need a little more help understanding what you want. Can you give me an example of the callback you want? E.g., is it
```julia
callback(filename)  # just passes the name of any watched file that changed
callback(revisions) # passes an object that encodes the specific changes made to the code
callback(...??)
```
In case you want to poke at Revise's code a little yourself, a key entry point is [`revise_file_now`](https://github.com/timholy/Revise.jl/blob/fde380eb51ff3900e690186cd4cd677a4c0251d0/src/Revise.jl#L213-L242). It receives an absolute path, computes a desired set of revisions (`revmd`), and then `eval`s the changes. Some extra complexity comes from distributed computing (evaling the diff on workers as well as the main process) and things like method deletion, but that's about it.

The `revmd` format, if that's what you need, is pretty simple. It's a Dict indexed by modules, and each value in the Dict has a set of expressions to be evaluated and method-signatures to be deleted.

I'm happy to make the changes myself, but I need a little more concrete info about what you're really asking for. If you don't want to dig into Revise's code (understandable), maybe a sketch of an API that you'd like to have, without worrying (yet) about how that would hook into Revise?

**Comment by essenciary** [comment]
If we focus on live reload as a first application of the callbacks, the workflow is like this: 
1 - there is an active websockets connection between the web browser and the web server
2 - when the web server finds about a change in relevant files, it sends a page reload message over the websocket 
3 - on the webpage, a JS forces a full page reload 

So on the server, we'd need a function, let's call it `WebServer.livereload(file)`. This function would have to be called by `Revise` when a file is changed. We can achieve this with something in the line of: 
```
Revise.callbacks.push!(module = :WebServer, function = :livereload)
```
Then, when a file is changed, `Revise` would invoke all the callbacks.

I imagine there will be challenges involving the functions being in scope and world age problems. So maybe `Revise` should do something like: 
```julia
@eval using WebServer # not sure if this is feasible
@eval WebServer invokelatest(livereload, file)
```

What do you think? If the logic is sound, I can take a stab at adding this. I'm concerned with the scope of the callbacks within `Revise`.

**Comment by timholy** [comment]
Please check https://github.com/timholy/Revise.jl/tree/teh/user_callbacks#user-callbacks, and if that seems OK also see #103. Let me know (preferably in #103) what changes need to be made.

**Comment by essenciary** [comment]
@timholy Thanks so much! A bit busy these days but I'll test and follow up ASAP.

**Comment by timholy** [comment]
I'll close this due to inactivity and a sense that this is orthogonal to Revise. The best approach is outlined in #203, and it's something that's easy to implement manually (and could be even better if `entr` gets added to the the FileWatching stdlib).
